//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingFilm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookingFilm()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
        }
    
        public int IdBooking { get; set; }
        public Nullable<System.DateTime> DateOrder { get; set; }
        public Nullable<int> IdCus { get; set; }
        public Nullable<int> IdTicket { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
