//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmGenre
    {
        public int FilmID { get; set; }
        public string IdGenre { get; set; }
        public string NameGenre { get; set; }
    
        public virtual Film Film { get; set; }
    }
}
