//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public int IdSeat { get; set; }
        public Nullable<int> IdRoom { get; set; }
        public string SeatName { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
