//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowTime
    {
        public int ShowtimeID { get; set; }
        public Nullable<int> FilmID { get; set; }
        public Nullable<int> IdRoom { get; set; }
        public Nullable<int> IdTicket { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Room Room { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
